const APPLICATION_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  WITHDRAWN: 'withdrawn'
}

const STATUS_LABELS = {
  [APPLICATION_STATUS.PENDING]: '待审批',
  [APPLICATION_STATUS.APPROVED]: '已通过',
  [APPLICATION_STATUS.REJECTED]: '已驳回',
  [APPLICATION_STATUS.WITHDRAWN]: '已撤回'
}

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATUS: 'INVALID_STATUS',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
}

module.exports = {
  APPLICATION_STATUS,
  STATUS_LABELS,
  ERROR_CODES
}
